export type CourseType = {
    Year: number,
    Term: string,
    YearTerm: string,
    Subject: string,
    Number: number,
    Name: string,
    Description: string,
    'Credit Hours': string,
    'Section Info': string,
    'Degree Attributes': string,
    'Schedule Information': string,
    CRN: number,
    Section: string,
    'Status Code': string,
    "Part of Term": number | string,
    'Section Title': string,
    "Section Credit Hours": string,
    "Section Status": string,
    "Enrollment Status": string,
    Type: string,
    'Type Code': string,
    'Start Time': string,
    'End Time': string,
    'Days of Week': string,
    Room: number | string,
    Building: string,
    Instructors: string,
}